import = ["/home/zero/.config/alacritty/themes/themes/tokyo-night.toml"]
live_config_reload = true

[env]
TERM = "screen-256color"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "Both"
title = "Juan's MacBook Pro"
