#!/usr/bin/env bash
export $(dbus-launch)

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

if [ command -v dunst ]; then
    dunst -conf "$SCRIPTPATH"/dunstrc
fi

if [ -x "$(command -v picom)" ]; then
    # picom &> /dev/null &
    picom --experimental-backends --config "$SCRIPTPATH"/picom.conf &> /dev/null &
    
fi

if [ -x "$(command -v feh)" ]; then
    feh --bg-fill "$SCRIPTPATH/wallpaper.jpg"
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#Applications
lxqt-policykit-agent &

if [ -x "$(command -v polybar)" ]; then
    pkill polybar
    index=0
    laptor_identifier="eDP-1"
    leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
    do
      monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
      if [ "$monitor" = "$laptor_identifier" ]; then
        monitor=$monitor polybar -c "$SCRIPTPATH"/polybar.ini mainbar1 &
      else
        monitor=$monitor polybar -c "$SCRIPTPATH"/polybar.ini mainbar2 &
      fi
      index=$((index+1))
    done
    
    # monitors="$(polybar -m | sed s/:.*// | tac)"
    # while read -r display; do
    #     MONITOR=$display polybar -c "$SCRIPTPATH/polybar.ini" mainbar &> /dev/null &
    # done <<< "$monitors"
    # exit 0
fi
